//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qwerty.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class venueinfo
    {
        public int Id { get; set; }
        public string Venue_Location { get; set; }
        public string Price { get; set; }
    }
}
